export {
  TelegramError,
  APIError,
  ValidationError,
  RateLimitError,
  NetworkError,
  TimeoutError,
  ParseError,
  PollingError,
  WebhookError,
  isTelegramError,
  isAPIError,
  isValidationError,
  isRateLimitError,
  isNetworkError,
  isTimeoutError,
  isParseError,
  isPollingError,
  isWebhookError,
} from './base';
